language: node_js
before_script:
  - npm install -g gulp
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
node_js:
  - "5.1"
  - "4.2"
  - "4.0"
  - "iojs"